### ISSUE TITLE
Possible to have a writeup on how to build linux version?

### ISSUE THREAD

**Issue by kenken64** [t-asano/tinyviewplus#30]
Possible to have a writeup on how to build linux version?

**Comment by kenken64** [comment]
ubuntu distribution

**Comment by t-asano** [comment]
I haven't tried it yet, but these docs might help.
https://github.com/t-asano/tinyviewplus/blob/master/docs/HowToBuild_en.md
https://openframeworks.cc/setup/linux-install/

**Comment by WombatControl** [comment]
I have been able to get TinyViewPlus working on Arch Linux, but it is not the most pleasant process right now. Here's the process for Arch, which would probably be similar to other distributions:

1. Install a nightly version of openFrameworks. There is a bug with gstreamer that is fixed in the nightly version right now but not in the current release. If you use a version of Gstreamer that is 1.18.X or lower you can use the current release. Or you can cheat, install the current version and then pull all the files the libs/openFramework/video folder of the nightly version and replace those in wherever openFrameworks was installed (which for Arch is /opt/openFrameworks). The process for compiling openFrameworks will vary from distro to distro, so I am mostly glossing over this part.

2. Go to wherever openFrameworks was installed then execute these commands:

```
cd addons/
git clone -b fix-of_v0.10 https://github.com/t-asano/ofxTrueTypeFontUC.git
git clone https://github.com/t-asano/ofxAruco.git
git clone https://github.com/kylemcdonald/ofxCv.git
git clone https://github.com/t-asano/ofxZxing.git
git clone https://github.com/t-asano/ofxJoystick.git
```

3. Next you want to install the projectGenerator. You can do that by starting in the root folder for openFramework (which again for Arch is /opt/openFrameworks). Go to the scripts/linux folder and execute the "compilePG.sh" script. You should get a folder called "projectGenerator-linux64" in your openFramework root folder. 

4. You want to run the "projectGenerator" app in that folder to create your new project. Give it the name tinyviewplus. Leave the Project Path field alone, but note that depending on where your openFrameworks root folder is you may need to change the permissions of the "myApps" folder - on Arch I just changed the group to "wheel". You should see a field to add your addons. Here are the ones you want, if any of those are missing, make sure that step 2 above completed successfully:

```
ofxOsc
ofxTrueTypeFontUC
ofxAruco
ofxCv
ofxOpenCv
ofxPoco
ofxZxing
ofxJoystick
ofxXmlSettings
```

5. Next you want to take the project shell that projectGenerator just created and merge it with the TinyViewPlus code from Github. First, start in the your openFrameworks root folder and enter the following commands (the cp command does not need an -r flag, BTW). If this fails, check to make sure your folder permissions are correct.

```
cd apps/myApps
mv tinyviewplus tvptemp
git clone https://github.com/t-asano/tinyviewplus.git
cp tvptemp/* tinyviewplus/
rm -r tvptemp
```

6. You now should have a working project folder. Go into the "tinyviewplus" project folder. You can then just enter a "make" command (or a "sudo make" if you have permissions issues). You should get a binary in the "bin" folder. Run that.

7. You will need an ROTG device for any video to show up - the app filters anything else out. If you want to test video but do not have a ROTG FPV receiver you will need to comment out the if statement starting at line 321 of "ofApp.cpp" in the source folder for the app. Just be sure to add that back in.

8. I am deliberately not including instructions for building this project with QT Creator. While you certainly could do that, it adds a lot of extra steps, such as making sure that QBS is installed and I find that just doing everything from the command line is faster and less irritating.
